apiVersion: v1
kind: ConfigMap
metadata:
  name: coraza-crs
  namespace: {{ .Release.Namespace }}
data:
  crs-setup.conf: |
    SecDefaultAction "phase:1,log,auditlog,pass"
    SecDefaultAction "phase:2,log,auditlog,pass"

  REQUEST-942-APPLICATION-ATTACK-SQLI.conf: |
    SecRule ARGS "@detectSQLi" \
      "id:942100,\
      phase:2,\
      block,\
      msg:'SQL Injection Attack Detected'"