apiVersion: v1
kind: ConfigMap
metadata:
  name: coraza-config
  namespace: {{ .Release.Namespace }}
data:
  coraza.conf: |
    SecRuleEngine On

    SecRequestBodyAccess On
    SecResponseBodyAccess Off

    SecAuditEngine RelevantOnly
    SecAuditLog /dev/stdout

    Include @crs-setup.conf
    Include @owasp_crs/*.conf