pipeline {
  agent any

  environment {
    TF_VAR_access_key = credentials('HWC_ACCESS_KEY')
    TF_VAR_secret_key = credentials('HWC_SECRET_KEY')
    TF_DIR = 'examples/basic-ecs'
    GIT_REPO = 'https://github.com/alejandromore/jenkins.git'
  }

  stages {

    stage('Checkout main') {
      steps {
        checkout([
          $class: 'GitSCM',
          branches: [[name: '*/main']],
          userRemoteConfigs: [[
            url: "${GIT_REPO}",
            credentialsId: 'github-creds'
          ]]
        ])
      }
    }

    stage('Terraform Init') {
      steps {
        dir("${TF_DIR}") {
          sh '''
            rm -rf .terraform
            terraform init
          '''
        }
      }
    }

    stage('Terraform Plan') {
      steps {
        dir("${TF_DIR}") {
          sh 'terraform plan -var-file="local.tfvars"'
        }
      }
    }

    stage('Terraform Apply') {
      steps {
        dir("${TF_DIR}") {
          sh 'terraform apply -auto-approve -var-file="local.tfvars"'
        }
      }
    }

    stage('Commit Terraform State') {
      steps {
        dir("${TF_DIR}") {
          withCredentials([usernamePassword(
            credentialsId: 'github-creds',
            usernameVariable: 'GIT_USER',
            passwordVariable: 'GIT_TOKEN'
          )]) {

            sh '''
              git config user.name "jenkins"
              git config user.email "jenkins@local"

              git status

              git add terraform.tfstate terraform.tfstate.backup || true

              git diff --cached --quiet || git commit -m "Update terraform state (build ${BUILD_NUMBER})"

              git push https://${GIT_USER}:${GIT_TOKEN}@github.com/USUARIO_REAL/jenkins.git HEAD:main
            '''
          }
        }
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: '**/*.log', allowEmptyArchive: true
    }
  }
}
