pipeline {
  agent any
  
  environment {
    TF_VAR_access_key = credentials('HWC_ACCESS_KEY')
    TF_VAR_secret_key = credentials('HWC_SECRET_KEY')
    TF_DIR = 'examples/basic-ecs'
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main',
            credentialsId: 'github-creds',
            url: 'https://github.com/${GIT_USER}/jenkins.git'
      }
    }

    stage('Terraform Init') {
      steps {
        dir("${TF_DIR}") {
          sh 'terraform init'
        }
      }
    }
    
    stage('Terraform Plan') {
      steps {
        dir("${TF_DIR}") {
          sh 'terraform plan -var-file="local.tfvars"'
        }
      }
    }
    
    stage('Terraform Apply') {
      steps {
        dir("${TF_DIR}") {
          sh 'terraform apply -auto-approve -var-file="local.tfvars"'
        }
      }
    }
    
    stage('Commit Terraform State') {
      steps {
        dir("${TF_DIR}") {
          withCredentials([usernamePassword(
            credentialsId: 'github-creds',
            usernameVariable: 'GIT_USER',
            passwordVariable: 'GIT_PASS'
          )]) {

            sh '''
              git config user.name "jenkins"
              git config user.email "jenkins@local"

              echo "Git status:"
              git status

              git add terraform.tfstate terraform.tfstate.backup || true

              git commit -m "Update terraform state from Jenkins build ${BUILD_NUMBER}" \
                || echo "No changes to commit"

              git push https://${GIT_USER}:${GIT_PASS}@github.com/${GIT_USER}/jenkins.git main
            '''
          }
        }
      }
    }

    stage('Commit Terraform State') {
      steps {
        dir("${TF_DIR}") {
          withCredentials([usernamePassword(
            credentialsId: 'github-creds',
            usernameVariable: 'GIT_USER',
            passwordVariable: 'GIT_TOKEN'
          )]) {

            sh '''
              git config user.name "jenkins"
              git config user.email "jenkins@local"

              git status

              git add terraform.tfstate terraform.tfstate.backup || true

              git commit -m "Update terraform state from Jenkins build ${BUILD_NUMBER}" || echo "No changes to commit"

              git push https://${GIT_USER}:${GIT_TOKEN}@github.com/${GIT_USER}/jenkins.git HEAD:main
            '''
          }
        }
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: '**/*.log', allowEmptyArchive: true
    }
  }
}
