FROM jenkins/inbound-agent:latest-jdk21

LABEL container.registry="acrgenesis" \
      image.name="agent-genesisBackJdk21" \
      version="1.0" \
      author="hfarroc" \
      commit-id="4149a50" \
      build.date="2026-03-03 18:00:00"

USER root

# Variables de entorno
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Instalar paquetes necesarios
RUN apt-get update && apt-get install -y \
    git \
    openssh-client \
    curl \
    jq \
    locales \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# Configurar locale UTF-8
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
 && locale-gen \
 && update-locale LANG=en_US.UTF-8

# Make bash the default shell
RUN ln -sf /bin/bash /bin/sh

USER jenkins