FROM jenkins/inbound-agent:latest-jdk21

LABEL container.registry="acrgenesis" \
      image.name="agent-huawei" \
      version="1.0" \
      author="hfarroc" \
      commit-id="4149a50" \
      build.date="2026-03-03 18:00:00"

USER root

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

ARG COSIGN_VERSION=2.0.2
ARG SOPS_VERSION=3.11.0

# Base packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        locales curl git wget jq unzip iptables procps xz-utils \
        ca-certificates gnupg lsb-release software-properties-common rsync ansible && \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen en_US.UTF-8

# Docker CLI
RUN wget https://download.docker.com/linux/static/stable/x86_64/docker-28.1.1.tgz && \
    tar xzvf docker-28.1.1.tgz && \
    cp docker/* /usr/local/bin/ && \
    rm -rf docker docker-28.1.1.tgz

# Huawei CLI
RUN curl -LO https://ap-southeast-3-hwcloudcli.obs.ap-southeast-3.myhuaweicloud.com/cli/latest/huaweicloud-cli-linux-amd64.tar.gz && \
    tar -zxvf huaweicloud-cli-linux-amd64.tar.gz && \
    chmod +x hcloud && \
    mv hcloud /usr/local/bin/

# kubectl
RUN KUBECTL_VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt) && \
    curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/

# helm
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && \
    chmod 700 get_helm.sh && \
    ./get_helm.sh && \
    rm get_helm.sh

# cosign
RUN wget https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign_${COSIGN_VERSION}_amd64.deb && \
    dpkg -i cosign_${COSIGN_VERSION}_amd64.deb && \
    rm cosign_${COSIGN_VERSION}_amd64.deb

# sops
RUN wget https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64 \
    -O /usr/local/bin/sops && \
    chmod +x /usr/local/bin/sops

# yq
RUN wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
    -O /usr/local/bin/yq && \
    chmod +x /usr/local/bin/yq

# Clean
RUN rm -rf /var/lib/apt/lists/* && apt-get clean

USER jenkins