pipeline {
    agent any

    options {
        disableConcurrentBuilds()
    }

    parameters {
        choice(
            name: 'ACTION',
            choices: ['deploy', 'destroy'],
            description: 'Acción sobre el ambiente'
        )
        booleanParam(
            name: 'RUN_TERRAFORM',
            defaultValue: true,
            description: 'Ejecutar Terraform'
        )
        booleanParam(
            name: 'RUN_ANSIBLE',
            defaultValue: false,
            description: 'Ejecutar Ansible'
        )
        booleanParam(
            name: 'RUN_HELM',
            defaultValue: false,
            description: 'Ejecutar Helm'
        )
    }

    environment {
        TF_VAR_access_key = credentials('hwc-access-key')
        TF_VAR_secret_key = credentials('hwc-secret-key')
        TF_DIR   = 'app-elb-cce-dew-rds/terraform'
        HELM_DIR = 'app-elb-cce-dew-rds/helm/postgresql'
        ANS_DIR  = 'app-elb-cce-dew-rds/ansible'
        DUMP_DB  = 'obs://obs-alejandro-db-dumps/pg-cliente-dump.sql'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            when {
                allOf {
                    expression { params.RUN_TERRAFORM }
                    expression { params.ACTION in ['deploy', 'destroy'] }
                }
            }
            steps {
                dir(env.TF_DIR) {
                sh '''
                    rm -rf .terraform
                    terraform init
                '''
                }
            }
        }

        stage('Terraform Plan') {
            when {
                allOf {
                    expression { params.ACTION == 'deploy' }
                    expression { params.RUN_TERRAFORM }
                }
            }
            steps {
                dir(env.TF_DIR) {
                    sh 'terraform plan -var-file="local.tfvars"'
                }
            }
        }

        stage('Terraform Apply') {
            when {
                allOf {
                    expression { params.ACTION == 'deploy' }
                    expression { params.RUN_TERRAFORM }
                }
            }
            steps {
                dir(env.TF_DIR) {
                    script {
                        sh 'terraform apply -auto-approve -var-file="local.tfvars"'

                        env.cluster_id = sh(
                            script: 'terraform output -raw cluster_id',
                            returnStdout: true
                        ).trim()
                        env.rds_public_ip = sh(
                            script: 'terraform output -raw rds_public_ip',
                            returnStdout: true
                        ).trim()
                        env.db_password = sh(
                            script: 'terraform output -raw rds_postgres_password',
                            returnStdout: true
                        ).trim()
                    }

                    // Pruebas: Guardar en archivos locales (workspace)
                    writeFile file: "${WORKSPACE}/cluster_id.txt", text: env.cluster_id
                    writeFile file: "${WORKSPACE}/rds_public_ip.txt", text: env.rds_public_ip
                    writeFile file: "${WORKSPACE}/db_password.txt", text: env.db_password
                }
            }
        }

        stage('Restore Database (Ansible)') {
            when {
                allOf {
                    expression { params.ACTION == 'deploy' }
                    expression { params.RUN_ANSIBLE }
                }
            }
            steps {

                // Leer outputs generados previamente
                dir(env.ANS_DIR) {
                    script {
                        rds_public_ip = readFile("${WORKSPACE}/rds_public_ip.txt").trim()
                        db_password   = readFile("${WORKSPACE}/db_password.txt").trim()
                    }
                }

                // Inyectar AK / SK desde Jenkins Credentials
                withCredentials([
                    string(credentialsId: 'hwc-access-key', variable: 'OBS_ACCESS_KEY'),
                    string(credentialsId: 'hwc-secret-key', variable: 'OBS_SECRET_KEY')
                ]) {

                    // Exportar variables Groovy → ENV para el shell
                    withEnv([
                        "RDS_PUBLIC_IP=${rds_public_ip}",
                        "DB_PASSWORD=${db_password}"
                    ]) {

                        dir(env.ANS_DIR) {
                            sh '''
                            set -euo pipefail

                            export HOME=$(mktemp -d)

                            echo "Starting DB restore"
                            echo "Target DB host: $RDS_PUBLIC_IP"

                            # Configurar obsutil (sin persistir credenciales)
                            obsutil config \
                            -i "$OBS_ACCESS_KEY" \
                            -k "$OBS_SECRET_KEY" \
                            -e obs.la-south-2.myhuaweicloud.com

                            # Descargar dump solo si no existe
                            if [ ! -s db_dump.sql ]; then
                            obsutil cp "$DUMP_DB" db_dump.sql -f
                            fi

                            test -s db_dump.sql || exit 1

                            # Variables para Ansible
                            export DB_HOST="$RDS_PUBLIC_IP"
                            export DB_PASSWORD="$DB_PASSWORD"

                            ansible-playbook \
                            -i inventory/hosts \
                            playbooks/restore-db.yml \
                            --extra-vars "db_dump_file=db_dump.sql"
                            '''
                        }
                    }
                }
            }
        }


        stage('Get kubeconfig') {
            when {
                allOf {
                    expression { params.ACTION == 'deploy' }
                    expression { params.RUN_HELM }
                }
            }
            steps {
                // Leer outputs generados previamente
                dir(env.ANS_DIR) {
                    script {
                        cluster_id    = readFile("${WORKSPACE}/cluster_id.txt").trim()
                    }
                }
                // Exportar variable Groovy → ENV para el shell
                dir(env.HELM_DIR) {
                    sh '''
                    echo "Generating kubeconfig for CCE cluster: ${env.cluster_id}"

                    huaweicloud cce cluster get-kubeconfig \
                        --cluster-id ${env.cluster_id} \
                        --file kubeconfig.yaml

                    chmod 600 kubeconfig.yaml
                    '''
                }
            }
        }

        stage('Helm Deploy App') {
            when {
                allOf {
                    expression { params.ACTION == 'deploy' }
                    expression { params.RUN_HELM }
                }
            }
            steps {
                dir(env.HELM_DIR) {
                    sh '''
                      helm upgrade --install app-basic-java helm/java-app  \
                        -n app-basic --create-namespace \
                        --wait
                    '''
                }
            }
        }

        stage('Terraform Destroy') {
            when {
                allOf {
                    expression { params.ACTION == 'destroy' }
                    expression { params.RUN_TERRAFORM }
                }
            }
            steps {
                dir(env.TF_DIR) {
                    sh 'terraform destroy -auto-approve -var-file="local.tfvars"'
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline ejecutado correctamente (${params.ACTION})"
        }
        failure {
            echo "Error en el pipeline"
        }
        //always {
        //    deleteDir()
        //}
    }
}
