@Library('shared-lib') _

pipeline {
    agent any

    options {
        disableConcurrentBuilds()
    }

    parameters {
        choice(
            name: 'ACTION',
            choices: ['deploy', 'destroy'],
            description: 'Acción sobre el ambiente'
        )
        booleanParam(
            name: 'RUN_TERRAFORM',
            defaultValue: false,
            description: 'Construir infraestructura con Terraform'
        )
        booleanParam(
            name: 'RUN_ANSIBLE',
            defaultValue: false,
            description: 'Restaurar base de datos con Ansible'
        )
        booleanParam(
            name: 'RUN_HELM',
            defaultValue: false,
            description: 'Desplegar la aplicación con Helm, se debe cargar el kubeconfig en el secreto cce-kubeconfig'
        )
    }

    environment {
        TF_VAR_access_key = credentials('hwc-access-key')
        TF_VAR_secret_key = credentials('hwc-secret-key')
        
        TF_DIR   = 'app-elb-cce-dew-rds/terraform'
        HELM_DIR = 'app-elb-cce-dew-rds/helm'
        ANS_DIR  = 'app-elb-cce-dew-rds/ansible'
        DUMP_DB  = 'obs://obs-alejandro-db-dumps/pg-cliente-dump.sql'
        REGION   = 'la-south-2'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Deploy') {
            when {
                expression { params.RUN_TERRAFORM }
            }
            steps {
                script {

                    terraformDeploy(
                        dir: env.TF_DIR,
                        varsFile: 'local.tfvars',
                        action: params.ACTION,
                        outputs: [
                            'cluster_id', 
                            'rds_public_ip', 
                            'rds_postgres_password', 
                            'elb_public_id', 
                            'elb_public_ip'
                        ]   // aquí defines qué outputs capturar
                    )

                }
            }
        }

        stage('Restore Database') {
            when {
                allOf {
                    expression { params.ACTION == 'deploy' }
                    expression { params.RUN_ANSIBLE }
                }
            }
            steps {
                script {

                    // Leer outputs generados por terraformDeploy
                    env.rds_public_ip = readFile("${WORKSPACE}/rds_public_ip.txt").trim()
                    env.rds_postgres_password = readFile("${WORKSPACE}/rds_postgres_password.txt").trim()

                    ansibleRestoreDb(
                        dir: env.ANS_DIR,
                        dump: env.DUMP_DB,
                        dbHost: env.rds_public_ip,
                        dbPassword: env.rds_postgres_password,
                        accessKeyCred: 'hwc-access-key',
                        secretKeyCred: 'hwc-secret-key'
                    )
                }
            }
        }

        stage('Helm Deploy Application') {
            when {
                allOf {
                    expression { params.ACTION == 'deploy' }
                    expression { params.RUN_HELM }
                }
            }
            steps {
                script {

                    env.elb_public_id = readFile("${WORKSPACE}/elb_public_id.txt").trim()
                    env.elb_public_ip = readFile("${WORKSPACE}/elb_public_ip.txt").trim()

                    helmDeployApp(
                        dir: env.HELM_DIR,
                        chartDir: 'java-app',
                        kubeconfigCred: 'cce-app-kubeconfig',
                        elbId: env.elb_public_id,
                        elbIp: env.elb_public_ip,
                        releaseName: 'app-basic-java',
                        namespace: 'app-basic',
                        healthEndpoint: '/app-java/healthCheck',
                        timeoutSeconds: 200
                    )
                }
            }
        }

    }

    post {
        success {
            echo "Pipeline ejecutado correctamente (${params.ACTION})"
        }
        failure {
            echo "Error en el pipeline"
        }
    }
}
