pipeline {
    agent any

    parameters {
        string(
            name: 'PRIVATE_KEY_NAME',
            defaultValue: 'basic-project-private-key',
            description: 'Nombre de private key (CSMS)'
        )
    }

    environment {
        TF_DIR = 'key-management/get-private-key'
        TF_VAR_access_key = credentials('hwc-access-key')
        TF_VAR_secret_key = credentials('hwc-secret-key')
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Init Terraform') {
            steps {
                dir("${env.TF_DIR}") {
                    sh 'terraform init'
                }
            }
        }

        stage('Get Public Key') {
            steps {
                dir("${env.TF_DIR}") {
                    // Mapeamos los IDs de Jenkins a las variables que Terraform entiende
                    withCredentials([
                        string(credentialsId: 'hwc-access-key', variable: 'HW_ACCESS_KEY'),
                        string(credentialsId: 'hwc-secret-key', variable: 'HW_SECRET_KEY')
                    ]) {
                        sh """
                            terraform init
                            terraform apply -auto-approve -var="private_key_name=${params.PRIVATE_KEY_NAME}"
                        """
                    }
                }
            }
        }

        stage('Mostrar identificador de KeyPair') {
            steps {
                dir("${env.TF_DIR}") {
                    sh 'terraform output private_key_content'
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline completado correctamente. La llave está creada y el identificador mostrado."
        }
        failure {
            echo "Error en el pipeline"
        }
    }
}
