apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-base
data:
  setup-base.sh: |
    #!/bin/bash
    set -e
    export DEBIAN_FRONTEND=noninteractive
    echo "Instalando dependencias necesarias..."

    apt-get update -qq
    apt-get install -y -qq \
        curl \
        jq \
        tar \
        python3-pip \
        ca-certificates
    
    pip install huaweicloudsdkcore huaweicloudsdkobs

    echo "Descargando obsutil..."
    curl -Lk "https://obs-community.obs.myhuaweicloud.com/obsutil/current/obsutil_linux_amd64.tar.gz" -o obsutil_linux_amd64.tar.gz
    
    tar -xzvf obsutil_linux_amd64.tar.gz
    FOLDER=$(ls -d obsutil_linux_amd64_*)
    mv $FOLDER/obsutil /usr/local/bin/
    chmod +x /usr/local/bin/obsutil

    echo "Setup finalizado."