apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-python-obs
data:
  obs-test.py: |
    from huaweicloudsdkcore.auth.credentials import WebIdentityCredentialsProvider
    from huaweicloudsdkobs.v3 import ObsClient

    provider = WebIdentityCredentialsProvider()

    obs = ObsClient(
        credentials_provider=provider,
        region="la-south-2"
    )

    resp = obs.list_buckets()

    print("Buckets disponibles:")
    for bucket in resp.buckets:
        print(bucket.name)