apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-test
  template:
    metadata:
      labels:
        app: pod-test
    spec:
      serviceAccountName: sa-obs-workload-identity

      containers:
      - name: pod-test
        image: ubuntu:22.04

        command:
        - /bin/bash
        - -c
        - |
          /scripts/setup-base.sh
          echo "Contenedor listo..."
          sleep infinity

        volumeMounts:
        - name: oidc-token
          mountPath: /var/run/secrets/tokens
          readOnly: true

        - name: setup-script
          mountPath: /scripts

      volumes:
      - name: oidc-token
        projected:
          sources:
          - serviceAccountToken:
              path: oidc-token
              expirationSeconds: 7200
              audience: huawei-cce

      - name: setup-script
        configMap:
          name: cm-base
          defaultMode: 0755