apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-test
  template:
    metadata:
      labels:
        app: pod-test
    spec:
      # 🔐 ServiceAccount mapeado en IAM
      serviceAccountName: sa-workload-identity

      containers:
      - name: pod-test
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "/opt/scripts/setup-test.sh"]

        volumeMounts:
        # Script desde ConfigMap
        - name: script-volume
          mountPath: /opt/scripts

        # Token OIDC proyectado
        - name: oidc-token
          mountPath: /var/run/secrets/tokens
          readOnly: true

      volumes:
      # ConfigMap con script de prueba
      - name: script-volume
        configMap:
          name: cm-test-setup
          defaultMode: 0755

      # 🔐 Token OIDC proyectado para Workload Identity
      - name: oidc-token
        projected:
          sources:
          - serviceAccountToken:
              path: oidc-token
              expirationSeconds: 7200
              audience: huawei-cce   # ← Debe coincidir EXACTAMENTE con client_id del Identity Provider