$env:HW_ACCESS_KEY="8ENLOAE2QCECKCRKANEU"
$env:HW_SECRET_KEY="vddTKjKuG8hcNGOb1cYv3jZ03RLlkOFEEhEHphl8"
$env:HW_REGION_NAME="la-south-2"

$env:AWS_ACCESS_KEY_ID="8ENLOAE2QCECKCRKANEU"
$env:AWS_SECRET_ACCESS_KEY="vddTKjKuG8hcNGOb1cYv3jZ03RLlkOFEEhEHphl8"

Write-Host "Variables cargadas"