@Library('shared-lib') _

pipeline {
    agent any

    options {
        disableConcurrentBuilds()
    }

    parameters {
        choice(
            name: 'ACTION',
            choices: ['deploy', 'destroy'],
            description: 'Acción sobre el ambiente'
        )
        booleanParam(
            name: 'RUN_TERRAFORM',
            defaultValue: false,
            description: 'Construir infraestructura con Terraform'
        )
        booleanParam(
            name: 'RUN_HELM',
            defaultValue: false,
            description: 'Desplegar Jenkins con Helm (cargar kubeconfig en secreto)'
        )
        booleanParam(
            name: 'CLEAN_WORKSPACE',
            defaultValue: false,
            description: 'Limpiar workspace'
        )
    }

    environment {
        TF_VAR_access_key = credentials('hwc-access-key')
        TF_VAR_secret_key = credentials('hwc-secret-key')
        TF_DIR   = 'tdp-config-catalog-cce/terraform'
        HELM_DIR = 'tdp-config-catalog-cce/helm'
        REGION   = 'la-south-2'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        // -----------------------------
        // Terraform: infraestructura
        // -----------------------------
        stage('Terraform Deploy') {
            when {
                expression { params.RUN_TERRAFORM }
            }
            steps {
                script {
                    terraformDeploy(
                        dir: env.TF_DIR,
                        varsFile: 'local.tfvars',
                        action: params.ACTION,
                        outputs: [
                            'elb_public_ip', 
                            'elb_public_id'
                        ]
                    )
                }
            }
        }

        // -----------------------------
        // Helm desplegar las aplicaciones
        // -----------------------------
        stage('Deploy Demo App to CCE') {

            when {
                expression { params.RUN_HELM }
            }

            environment {
                NAMESPACE = "demo-app"
                RELEASE_NAME = "demo-app"
                TIMEOUT_SECONDS = "300"
            }

            steps {
                script {
                    // Lectura de archivos generados en stages previos
                    env.elb_public_id = readFile("${WORKSPACE}/elb_public_id.txt").trim()
                    env.elb_public_ip = readFile("${WORKSPACE}/elb_public_ip.txt").trim()
                }
                dir(env.HELM_DIR) {

                    withCredentials([
                        file(credentialsId: 'cce-app-kubeconfig', variable: 'KUBECONFIG'),
                        file(credentialsId: 'sops-gpg-key', variable: 'GPG_KEY_FILE')
                    ]) {

                        sh '''
                        set -eo pipefail

                        export KUBECONFIG=$KUBECONFIG

                        echo "=========================================="
                        echo "Importando llave GPG para SOPS..."
                        echo "=========================================="

                        # Aislar entorno GPG (best practice)
                        export GNUPGHOME=$(mktemp -d)

                        gpg --batch --import $GPG_KEY_FILE

                        echo ""
                        echo "=========================================="
                        echo "Desencriptando secrets..."
                        echo "=========================================="

                        sops -d demo-app/secrets/secrets-enc.yaml > demo-app/templates/secret.yaml

                        echo ""
                        echo "=========================================="
                        echo "Validando acceso al cluster CCE..."
                        echo "=========================================="

                        kubectl get nodes

                        echo ""
                        echo "=========================================="
                        echo "Desplegando Helm Release: ${RELEASE_NAME}"
                        echo "Namespace: ${NAMESPACE}"
                        echo "Chart Dir: demo-app"
                        echo "=========================================="

                        helm upgrade --install ${RELEASE_NAME} ./demo-app \
                        -n ${NAMESPACE} \
                        --create-namespace \
                        --wait \
                        --timeout ${TIMEOUT_SECONDS}s \
                        --set elb.id=${elb_public_id}


                        echo ""
                        echo "=========================================="
                        echo "Iniciando Health Check ..."
                        echo "ELB IP: ${elb_public_ip}"
                        echo "=========================================="

                        for i in \$(seq 1 30); do
                        echo "Intento \$i..."
                        if curl -sf http://${elb_public_ip}/config-server.html > /dev/null; then
                            echo ""
                            echo "App disponible."
                            exit 0
                        fi
                        sleep 10
                        done

                        echo ""
                        echo "ERROR: No respondió después de múltiples intentos."
                        exit 1


                        '''
                    }
                }
            }
        }

        // -----------------------------
        // Clean Workspace
        // -----------------------------
        stage('Clean Workspace') {
            when {
                expression { params.CLEAN_WORKSPACE }
            }
            steps {
                deleteDir()
            }
        }
    }

    post {
        success {
            echo "Pipeline ejecutado correctamente (${params.ACTION})"
        }
        failure {
            echo "Error en el pipeline"
        }
    }
}
