- hosts: jenkins
  become: true

  tasks:

    - name: Install Docker
      apt:
        name:
          - docker.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Create Jenkins directory
      file:
        path: /opt/jenkins
        state: directory

    - name: Copy docker compose
      copy:
        src: files/docker-compose.yml
        dest: /opt/jenkins/docker-compose.yml

    - name: Copy JCasC config
      copy:
        src: files/casc.yaml
        dest: /opt/jenkins/casc.yaml

    - name: Template env file
      template:
        src: templates/jenkins.env.j2
        dest: /opt/jenkins/jenkins.env

    - name: Start Jenkins
      shell: docker compose up -d
      args:
        chdir: /opt/jenkins