{{- if and .Values.demoClient.enabled (eq .Values.demoClient.exposure.type "ingress") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-client
  labels:
    app: demo-client
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-client
                port:
                  number: {{ .Values.demoClient.port }}
{{- end }}