@Library('shared-lib') _

pipeline {
    agent { label 'agent-huawei' }

    options {
        disableConcurrentBuilds()
    }

    parameters {
        choice(
            name: 'ACTION',
            choices: ['deploy', 'destroy'],
            description: 'Acción sobre el ambiente'
        )
        booleanParam(
            name: 'RUN_TERRAFORM',
            defaultValue: false,
            description: 'Construir infraestructura con Terraform'
        )
        booleanParam(
            name: 'RUN_ANSIBLE',
            defaultValue: false,
            description: 'Instalar Docker e imagen Jenkins'
        )
        string(
            name: 'ECS_PUBLIC_IP',
            defaultValue: '101.44.3.15',
            description: 'IP pública del ECS donde se desplegará Jenkins'
        )

        base64File(
            name: 'ECS_PRIVATE_KEY',
            description: 'Subir archivo de clave privada SSH'
        )
    }

    environment {
        TF_IN_AUTOMATION = "true"
        TF_CLI_ARGS = "-no-color"
        TF_DIR   = 'tdp-jenkins-ecs/terraform'
        ANS_DIR  = 'tdp-jenkins-ecs/ansible'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Deploy') {
            when {
                expression { params.RUN_TERRAFORM }
            }
            steps {
                withCredentials([
                    string(credentialsId: 'hwc-access-key', variable: 'HW_ACCESS_KEY'),
                    string(credentialsId: 'hwc-secret-key', variable: 'HW_SECRET_KEY'),
                    string(credentialsId: 'hwc-access-key', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'hwc-secret-key', variable: 'AWS_SECRET_ACCESS_KEY')
                ]) {
                    script {

                        terraformDeploy(
                            dir: env.TF_DIR,
                            varsFile: 'local.tfvars',
                            action: params.ACTION,
                            outputs: ['ecs_public_ip', 'ecs_private_key'] 
                        )

                    }
                }
            }
        }

        stage('Deploy App with Ansible') {

            when {
                allOf {
                    expression { params.ACTION == 'deploy' }
                    expression { params.RUN_ANSIBLE }
                }
            }

            steps {
                script {

                    env.ecs_public_ip = params.ECS_PUBLIC_IP
                    env.ecs_private_key = "${WORKSPACE}/ecs_private_key.pem"

                    writeFile(
                        file: env.ecs_private_key,
                        text: new String(params.ECS_PRIVATE_KEY.decodeBase64())
                    )
                }
                // Ejecutar el playbook de instalacion
                dir(env.ANS_DIR) {

                    withCredentials([
                        usernamePassword(credentialsId: 'github-creds', usernameVariable: 'GITHUB_USER', passwordVariable: 'GITHUB_TOKEN'),
                        usernamePassword(credentialsId: 'swr-jenkins', usernameVariable: 'SWR_USER', passwordVariable: 'SWR_PASS'),
                        string(credentialsId: 'hwc-access-key', variable: 'HWC_ACCESS_KEY'),
                        string(credentialsId: 'hwc-secret-key', variable: 'HWC_SECRET_KEY')
                    ]) {

                        sh """
                            set -e
                            chmod 600 ${env.ecs_private_key}
                            
                            # Deshabilitar host key checking
                            export ANSIBLE_HOST_KEY_CHECKING=False

                            # Ejecutar playbook con todas las credenciales
                            ansible-playbook -i inventory/hosts playbook/deploy.yml \\
                                --private-key ${env.ecs_private_key} \\
                                --extra-vars "ansible_host=${env.ecs_public_ip} \\
                                            github_user=${GITHUB_USER} \\
                                            github_token=${GITHUB_TOKEN} \\
                                            swr_user=${SWR_USER} \\
                                            swr_password=${SWR_PASS} \\
                                            hwc_access_key=${HWC_ACCESS_KEY} \\
                                            hwc_secret_key=${HWC_SECRET_KEY}"

                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline ejecutado correctamente (${params.ACTION})"
        }
        failure {
            echo "Error en el pipeline"
        }
        //always {
        //    deleteDir()
        //}
    }
}
