@Library('shared-lib') _

pipeline {
    agent any

    options {
        disableConcurrentBuilds()
    }

    parameters {
        choice(
            name: 'ACTION',
            choices: ['deploy', 'destroy'],
            description: 'Acción sobre el ambiente'
        )
        booleanParam(
            name: 'RUN_TERRAFORM',
            defaultValue: false,
            description: 'Construir infraestructura con Terraform'
        )
        booleanParam(
            name: 'RUN_ANSIBLE',
            defaultValue: false,
            description: 'Instalar Docker e imagen Jenkins'
        )
    }

    environment {
        TF_IN_AUTOMATION = "true"
        TF_CLI_ARGS = "-no-color"
        TF_DIR   = 'tdp-jenkins-ecs/terraform'
        ANS_DIR  = 'tdp-jenkins-ecs/ansible'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Deploy') {
            when {
                expression { params.RUN_TERRAFORM }
            }
            steps {
                withCredentials([
                    string(credentialsId: 'hwc-access-key', variable: 'HW_ACCESS_KEY'),
                    string(credentialsId: 'hwc-secret-key', variable: 'HW_SECRET_KEY'),
                    string(credentialsId: 'hwc-access-key', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'hwc-secret-key', variable: 'AWS_SECRET_ACCESS_KEY')
                ]) {
                    script {

                        terraformDeploy(
                            dir: env.TF_DIR,
                            varsFile: 'local.tfvars',
                            action: params.ACTION,
                            outputs: ['ecs_public_ip', 'ecs_private_key'] 
                        )

                    }
                }
            }
        }

        stage('Deploy App with Ansible') {

            when {
                allOf {
                    expression { params.ACTION == 'deploy' }
                    expression { params.RUN_ANSIBLE }
                }
            }

            steps {
                // Ejecutar el playbook de instalacion
                dir(env.ANS_DIR) {

                    withCredentials([
                        string(credentialsId: 'hwc-access-key', variable: 'HW_ACCESS_KEY'),
                        string(credentialsId: 'hwc-secret-key', variable: 'HW_SECRET_KEY'),
                    ]) {
                        script {
                            env.ecs_public_ip = "${env.WORKSPACE}/ecs_public_ip.txt"
                            env.ecs_private_key = "${env.WORKSPACE}/ecs_private_key.txt"
                        }

                        sh """
                            set -e
                            chmod 600 ${env.ecs_private_key}
                            
                            # Deshabilitar host key checking
                            export ANSIBLE_HOST_KEY_CHECKING=False

                            # Ejecutar playbook con todas las credenciales
                            ansible-playbook -i inventory/hosts playbook/deploy.yml \\
                                --private-key ${env.ecs_private_key} \\
                                --extra-vars "ansible_host=${env.ecs_public_ip} \\
                                            hw_access_key=${HW_ACCESS_KEY} \\
                                            hw_secret_key=${HW_SECRET_KEY} "
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline ejecutado correctamente (${params.ACTION})"
        }
        failure {
            echo "Error en el pipeline"
        }
        always {
            deleteDir()
        }
    }
}
