{{- if .Values.configServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: {{ .Values.configServer.replicaCount }}
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: "{{ .Values.configServer.image.registry }}/{{ .Values.configServer.image.organization }}/{{ .Values.configServer.image.repository }}:{{ .Values.configServer.image.tag }}"
          imagePullPolicy: {{ .Values.configServer.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.configServer.port }}
          #envFrom:
          #  - secretRef:
          #      name: {{ .Values.configServer.secretName }}
          env:
          - name: GIT_URI
            valueFrom:
              secretKeyRef:
                name: ms-app-config-server-keyvault-secrets
                key: GIT_URI
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: ms-app-config-server-keyvault-secrets
                key: GIT_USERNAME
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: ms-app-config-server-keyvault-secrets
                key: GIT_TOKEN
          - name: HUAWEI_CLOUD_REGION
            valueFrom:
              secretKeyRef:
                name: ms-app-config-server-keyvault-secrets
                key: HUAWEI_CLOUD_REGION
          - name: HUAWEI_CLOUD_PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: ms-app-config-server-keyvault-secrets
                key: HUAWEI_CLOUD_PROJECT_ID
          - name: HUAWEI_CLOUD_AK
            valueFrom:
              secretKeyRef:
                name: ms-app-config-server-keyvault-secrets
                key: HUAWEI_CLOUD_AK
          - name: HUAWEI_CLOUD_SK
            valueFrom:
              secretKeyRef:
                name: ms-app-config-server-keyvault-secrets
                key: HUAWEI_CLOUD_SK
          - name: HUAWEI_CLOUD_SECRET_NAME
            valueFrom:
              secretKeyRef:
                name: ms-app-config-server-keyvault-secrets
                key: HUAWEI_CLOUD_SECRET_NAME


      imagePullSecrets:
        - name: default-secret
{{- end }}