apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-test
  template:
    metadata:
      labels:
        app: pod-test
    spec:
      serviceAccountName: sa-app-dev-dew
      containers:
      - name: pod-test
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "sleep infinity"]
        # Monta el volumen
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true

      volumes:
      # Define el volumen del SPC
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          fsType: ext4
          volumeAttributes:
            secretProviderClass: "app-dev-huawei-dew"