{{- if .Values.secretsStoreCreds.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-store-creds
type: Opaque
stringData:
  access_key: {{ .Values.secretsStoreCreds.access_key | quote }}
  secret_key: {{ .Values.secretsStoreCreds.secret_key | quote }}
{{- end }}