jenkins:
  clouds:
    - docker:
        name: "docker"

        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"

        templates:
          - labelString: "agent-terraform"
            name: "agent-terraform"
            mode: EXCLUSIVE
            pullStrategy: PULL_ALWAYS
            retentionStrategy:
              idleMinutes: 5
            remoteFs: "/home/jenkins"
            connector:
              attach:
                user: "jenkins"
            dockerTemplateBase:
              image: "swr.la-south-2.myhuaweicloud.com/cce-jenkins-integration-organization/jenkins-agent-terraform:1.0"
              pullCredentialsId: "swr-jenkins"
              tty: true
              mounts:
                - "type=bind,source=/opt/jenkins/workspaces,target=/home/jenkins/workspace"

          - labelString: "agent-huawei"
            name: "agent-huawei"
            mode: EXCLUSIVE
            pullStrategy: PULL_ALWAYS
            retentionStrategy:
              idleMinutes: 5
            remoteFs: "/home/jenkins"
            connector:
              attach:
                user: "jenkins"
            dockerTemplateBase:
              image: "swr.la-south-2.myhuaweicloud.com/cce-jenkins-integration-organization/jenkins-agent-huawei:1.0"
              pullCredentialsId: "swr-jenkins"
              tty: true
              mounts:
                - "type=bind,source=/opt/jenkins/workspaces,target=/home/jenkins/workspace"

          - labelString: "genesisBackJdk21"
            name: "genesisBackJdk21"
            mode: EXCLUSIVE
            pullStrategy: PULL_ALWAYS
            retentionStrategy:
              idleMinutes: 5
            remoteFs: "/home/jenkins"
            connector:
              attach:
                user: "jenkins"
            dockerTemplateBase:
              image: "swr.la-south-2.myhuaweicloud.com/cce-jenkins-integration-organization/jenkins-genesisbackjdk21:1.0"
              pullCredentialsId: "swr-jenkins"
              tty: true
              mounts:
                - "type=bind,source=/opt/jenkins/workspaces,target=/home/jenkins/workspace"
                - "type=bind,source=/opt/jenkins/.m2,target=/home/jenkins/.m2"

          - labelString: "genesisFrontNodeLTS"
            name: "genesisFrontNodeLTS"
            mode: EXCLUSIVE
            pullStrategy: PULL_ALWAYS
            retentionStrategy:
              idleMinutes: 5
            remoteFs: "/home/jenkins"
            connector:
              attach:
                user: "jenkins"
            dockerTemplateBase:
              image: "swr.la-south-2.myhuaweicloud.com/cce-jenkins-integration-organization/jenkins-genesisfrontnodelts:1.0"
              pullCredentialsId: "swr-jenkins"
              tty: true
              mounts:
                - "type=bind,source=/opt/jenkins/workspaces,target=/home/jenkins/workspace"
                - "type=bind,source=/opt/jenkins/.m2,target=/home/jenkins/.m2"

          - labelString: "genesisDeploySecureLTS"
            name: "genesisDeploySecureLTS"
            mode: EXCLUSIVE
            pullStrategy: PULL_ALWAYS
            retentionStrategy:
              idleMinutes: 5
            remoteFs: "/home/jenkins"
            connector:
              attach:
                user: "jenkins"
            dockerTemplateBase:
              image: "swr.la-south-2.myhuaweicloud.com/cce-jenkins-integration-organization/jenkins-genesisdeploysecurelts:1.0"
              pullCredentialsId: "swr-jenkins"
              tty: true
              extraGroups:
                - "988"
              mounts:
                - "type=bind,source=/opt/jenkins/workspaces,target=/home/jenkins/workspace"
                - "type=bind,source=/opt/jenkins/.m2,target=/home/jenkins/.m2"
                - "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock"

          - labelString: "genesisHuawei"
            name: "genesisHuawei"
            mode: EXCLUSIVE
            pullStrategy: PULL_ALWAYS
            retentionStrategy:
              idleMinutes: 5
            remoteFs: "/home/jenkins"
            connector:
              attach:
                user: "jenkins"
            dockerTemplateBase:
              image: "swr.la-south-2.myhuaweicloud.com/cce-jenkins-integration-organization/jenkins-genesishuawei:1.0"
              pullCredentialsId: "swr-jenkins"
              tty: true
              extraGroups:
                - "988"
              mounts:
                - "type=bind,source=/opt/jenkins/workspaces,target=/home/jenkins/workspace"
                - "type=bind,source=/opt/jenkins/.m2,target=/home/jenkins/.m2"
                - "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock"

          - labelString: "genesisSecrets"
            name: "genesisSecrets"
            mode: EXCLUSIVE
            pullStrategy: PULL_ALWAYS
            retentionStrategy:
              idleMinutes: 5
            remoteFs: "/home/jenkins"
            connector:
              attach:
                user: "jenkins"
            dockerTemplateBase:
              image: "swr.la-south-2.myhuaweicloud.com/cce-jenkins-integration-organization/jenkins-genesissecrets:1.0"
              pullCredentialsId: "swr-jenkins"
              tty: true
              mounts:
                - "type=bind,source=/opt/jenkins/workspaces,target=/home/jenkins/workspace"

          - labelString: "genesisImageScan"
            name: "genesisImageScan"
            mode: EXCLUSIVE
            pullStrategy: PULL_ALWAYS
            retentionStrategy:
              idleMinutes: 5
            remoteFs: "/home/jenkins"
            connector:
              attach:
                user: "jenkins"
            dockerTemplateBase:
              image: "swr.la-south-2.myhuaweicloud.com/cce-jenkins-integration-organization/jenkins-genesisimagescan:1.0"
              pullCredentialsId: "swr-jenkins"
              tty: true
              extraGroups:
                - "988"
              mounts:
                - "type=bind,source=/opt/jenkins/workspaces,target=/home/jenkins/workspace"
                - "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock"

          - labelString: "dockerNotifier"
            name: "dockerNotifier"
            mode: EXCLUSIVE
            pullStrategy: PULL_ALWAYS
            retentionStrategy:
              idleMinutes: 5
            remoteFs: "/home/jenkins"
            connector:
              attach:
                user: "jenkins"
            dockerTemplateBase:
              image: "swr.la-south-2.myhuaweicloud.com/cce-jenkins-integration-organization/jenkins-dockernotifier:1.0"
              pullCredentialsId: "swr-jenkins"
              tty: true
              mounts:
                - "type=bind,source=/opt/jenkins/workspaces,target=/home/jenkins/workspace"