jenkins:
  systemMessage: "Jenkins Docker Setup with SWR"
  numExecutors: 0

  securityRealm: none
  authorizationStrategy: unsecured

unclassified:
  location:
    url: "http://jenkins:8080/"
    adminAddress: "admin@localhost"