@Library('shared-lib') _

pipeline {
    agent { label 'docker-agent' }

    parameters {
        choice(
            name: 'ACTION',
            choices: ['deploy', 'destroy'],
            description: 'Acción sobre el ambiente'
        )
        choice(
            name: 'TEAM',
            choices: ['app1-dev'],
            description: 'Huawei Cloud Account'
        )

        string(
            name: 'VPC_CIDR',
            defaultValue: '10.4.0.0/16',
            description: 'VPC CIDR block'
        )

        string(
            name: 'VPC_SUBNET_PUBLIC_CIDR',
            defaultValue: '10.4.0.0/19',
            description: 'Subnet CIDR block'
        )

        string(
            name: 'VPC_SUBNET_CCE_CIDR',
            defaultValue: '10.4.32.0/19',
            description: 'Subnet CIDR block'
        )

        string(
            name: 'VPC_SUBNET_CCE_ENI_CIDR',
            defaultValue: '10.4.64.0/19',
            description: 'Subnet CIDR block'
        )

        choice(
            name: 'VM_SIZE',
            choices: [
                'c7n.xlarge.2',
                'c7n.large.2',
                'c6.large.2'
            ],
            description: 'ECS flavor for worker nodes'
        )

        string(
            name: 'NUM_NODES',
            defaultValue: '2',
            description: 'Number of worker nodes'
        )

        string(
            name: 'MAX_PODS',
            defaultValue: '90',
            description: 'Maximum Pods per node'
        )

        choice(
            name: 'AZ_LOCATION',
            choices: ['AZ1', 'AZ2'],
            description: 'Availability Zone'
        )
    }

    environment {
        TF_IN_AUTOMATION = "true"
        TF_CLI_ARGS = "-no-color"

        TF_DIR   = 'tdp-deploy-cloud-platform/terraform'
    }

    stages {

        stage('Generate terraform files') {
            when {
                allOf {
                    expression { params.ACTION == 'deploy' }
                }
            }
            steps {
                dir(env.TF_DIR) {
                    sh '''
                    export VPC_CIDR=${VPC_CIDR}
                    export VPC_SUBNET_PUBLIC_CIDR=${VPC_SUBNET_PUBLIC_CIDR}
                    export VPC_SUBNET_CCE_CIDR=${VPC_SUBNET_CCE_CIDR}
                    export VPC_SUBNET_CCE_ENI_CIDR=${VPC_SUBNET_CCE_ENI_CIDR}
                    export TEAM=${TEAM}

                    envsubst < local.tfvars.tpl > local.tfvars
                    envsubst < backend.tf.tpl > backend.tf
                    '''
                }
            }
        }


        stage('Terraform Deploy') {
            steps {
                script {

                    terraformDeploy(
                        dir: env.TF_DIR,
                        varsFile: 'local.tfvars',
                        action: params.ACTION,
                        outputs: [] 
                    )

                }
            }
        }

    }

    post {
        success {
            echo "Deployment completed successfully 🚀"
        }
        failure {
            echo "Deployment failed ❌"
        }
    }
}