version: "3.9"

services:

  postgresql:
    image: postgres:13
    container_name: artifactory-postgres
    environment:
      POSTGRES_DB: artifactory
      POSTGRES_USER: artifactory
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped


  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.77.11
    container_name: artifactory
    depends_on:
      - postgresql

    ports:
      - "8081:8081"
      - "8082:8082"

    environment:
      JF_SHARED_DATABASE_TYPE: postgresql
      JF_SHARED_DATABASE_DRIVER: org.postgresql.Driver
      JF_SHARED_DATABASE_URL: jdbc:postgresql://postgresql:5432/artifactory
      JF_SHARED_DATABASE_USERNAME: artifactory
      JF_SHARED_DATABASE_PASSWORD: password

    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory
      - ./bootstrap/access/bootstrap.creds:/opt/jfrog/artifactory/var/etc/access/bootstrap.creds

    restart: unless-stopped


volumes:

  postgres-data:
  artifactory-data: