version: "3.8"

services:

  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.77.11
    container_name: artifactory

    ports:
      - "8081:8081"
      - "8082:8082"

    environment:
      JF_SHARED_NODE_IP: 127.0.0.1

    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory

    restart: unless-stopped

volumes:
  artifactory-data: