pipeline {
  agent any

  environment {
    TF_VAR_access_key = credentials('HWC_ACCESS_KEY')
    TF_VAR_secret_key = credentials('HWC_SECRET_KEY')
  }

  stages {

    stage('Checkout') {
      steps {
        git credentialsId: 'github-creds',
            url: 'https://github.com/huawei-delivery-peru/huaweicloud-terraform.git'
      }
    }

    stage('Terraform Init') {
      steps {
        dir('examples/basic-app-ecs-dew-rds') {
          sh 'terraform init'
        }
      }
    }
    
    stage('Terraform Plan') {
      steps {
        dir('examples/basic-app-ecs-dew-rds') {
          sh 'terraform plan -var-file="local.tfvars"'
        }
      }
    }
    
    stage('Terraform Apply') {
      steps {
        dir('examples/basic-app-ecs-dew-rds') {
          sh 'terraform apply -auto-approve -var-file="local.tfvars"'
        }
      }
    }
    
    stage('Get Terraform Outputs') {
      steps {
        dir('examples/basic-app-ecs-dew-rds') {
          script {
            env.ecs_public_name = sh(
              script: "terraform output -raw ecs_public_name",
              returnStdout: true
            ).trim()

            env.ecs_public_ip = sh(
              script: "terraform output -raw ecs_public_ip",
              returnStdout: true
            ).trim()

            env.rds_name = sh(
              script: "terraform output -raw rds_name",
              returnStdout: true
            ).trim()

            env.rds_private_ip = sh(
              script: "terraform output -raw rds_name_ip",
              returnStdout: true
            ).trim()
            
            env.rds_public_ip = sh(
              script: "terraform output -raw rds_public_ip",
              returnStdout: true
            ).trim()
            
            env.PEM = sh(
              script: "terraform output -raw ecs_pem_path",
              returnStdout: true
            ).trim()
          }
        }
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: '**/*.log', allowEmptyArchive: true
    }
  }
}
